import {
  ScissorsIcon,
  SparklesIcon,
  HeartIcon,
  StarIcon,
  MoonIcon,
  SunIcon,
  EyeIcon,
  GiftIcon,
  TagIcon,
  CreditCardIcon,
  PercentIcon,
  AlertCircleIcon,
  InfoIcon,
  FilterIcon,
  BuildingIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  EditIcon,
  ListIcon,
  TrophyIcon,
  LightbulbIcon,
  MonitorIcon,
  ShoppingCartIcon,
  PrinterIcon,
  ShareIcon,
  ReceiptIcon,
  ArchiveIcon,
  RefreshIcon,
  CopyIcon,
  ShieldIcon,
  MessageSquareIcon,
  FileTextIcon,
  SendIcon,
  ActivityIcon,
  CakeIcon,
  WifiIcon,
  ChairIcon,
  CoffeeIcon,
  HistoryIcon,
  PlayIcon,
  LinkIcon,
  ShoppingBagIcon,
  TicketIcon,
  ThumbsUpIcon,
  WalletIcon,
  BankIcon,
  ScanIcon,
  ServiceIcon,
} from "@/components/icons";

const ICON_MAP: Record<string, React.ComponentType<any>> = {
  Scissors: ScissorsIcon,
  Sparkles: SparklesIcon,
  Heart: HeartIcon,
  Star: StarIcon,
  Moon: MoonIcon,
  Sun: SunIcon,
  Eye: EyeIcon,
  Gift: GiftIcon,
  Tag: TagIcon,
  CreditCard: CreditCardIcon,
  Percent: PercentIcon,
  AlertCircle: AlertCircleIcon,
  Info: InfoIcon,
  Filter: FilterIcon,
  Building: BuildingIcon,
  TrendingUp: TrendingUpIcon,
  TrendingDown: TrendingDownIcon,
  Edit: EditIcon,
  List: ListIcon,
  Trophy: TrophyIcon,
  Lightbulb: LightbulbIcon,
  Monitor: MonitorIcon,
  ShoppingCart: ShoppingCartIcon,
  Printer: PrinterIcon,
  Share: ShareIcon,
  Receipt: ReceiptIcon,
  Archive: ArchiveIcon,
  Refresh: RefreshIcon,
  Copy: CopyIcon,
  Shield: ShieldIcon,
  MessageSquare: MessageSquareIcon,
  FileText: FileTextIcon,
  Send: SendIcon,
  Activity: ActivityIcon,
  Cake: CakeIcon,
  Wifi: WifiIcon,
  Chair: ChairIcon,
  Coffee: CoffeeIcon,
  History: HistoryIcon,
  Play: PlayIcon,
  Link: LinkIcon,
  ShoppingBag: ShoppingBagIcon,
  Ticket: TicketIcon,
  ThumbsUp: ThumbsUpIcon,
  Wallet: WalletIcon,
  Bank: BankIcon,
  Scan: ScanIcon,
  Service: ServiceIcon,
};

export function getIconComponent(iconName?: string) {
  if (!iconName) return null;
  return ICON_MAP[iconName] || null;
}
